# Generated by Django 5.1 on 2024-08-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_date_coment_crated_at_coment_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coment',
            old_name='author',
            new_name='user',
        ),
    ]
